language: node_js
node_js:
  - '6'
deploy:
  # keep the build we just made with "npm test" (dist/)
  skip_cleanup: true

  # define the script to use for deployment
  provider: script
  script: ./scripts/deploy.sh

  # only run on one version of node (v5 here)
  on:
    branch: master # ⚠️ OR SRC IF YOU USE USERNAME.GITHUB.IO
