// Generated by Wrangler on Wed May 29 2024 15:46:47 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

interface Env {
	SANITY_STUDIO_PROJECT_ID: "pfnv96lh";
	SANITY_STUDIO_DATASET: "main";
	SANITY_STUDIO_URL: "http://localhost:3333";
	SANITY_STUDIO_STEGA_ENABLED: "true";
}
